import { Metadata } from "next"
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "Default title",
    default: "%s | Lightness",
    absolute: ""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">

      <body>
        <header

        >

        </header>
        {children}

        <footer

        >

        </footer>

      </body>



    </html>
  )
}
